name: Firebase CI/CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install Functions deps
        working-directory: functions
        run: npm ci

      - name: Lint Functions (skip if not configured)
        working-directory: functions
        run: |
          if [ -f .eslintrc.js ] || [ -f .eslintrc.cjs ] || [ -f .eslintrc.json ]; then
            npx eslint . || true
          else
            echo "No eslint config; skipping"
          fi

      - name: Deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: firebase deploy --only functions,firestore:rules,firestore:indexes,storage:rules --non-interactive --project ${{ secrets.FIREBASE_PROJECT_ID }}
